"""update columns for shop

Revision ID: 61075f5fb347
Revises: becbc996126f
Create Date: 2026-07-10 15:53:52.201809

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "61075f5fb347"
down_revision: Union[str, Sequence[str], None] = "becbc996126f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("product", sa.Column("units_sold", sa.Integer(), nullable=False))
    op.add_column("rarity", sa.Column("order", sa.Integer(), nullable=False))
    op.add_column("sale", sa.Column("slug", sa.Text(), nullable=False))

    op.drop_column("sale", "start_at")
    op.drop_column("sale", "end_at")
    op.drop_column("sale", "name")

    op.add_column("sale", sa.Column("start_at", sa.DATETIME(), nullable=False))
    op.add_column("sale", sa.Column("end_at", sa.DATETIME(), nullable=False))
    op.add_column("sale", sa.Column("name", sa.TEXT(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_column("sale", "start_at")
    op.drop_column("sale", "end_at")
    op.drop_column("sale", "name")

    op.add_column("sale", sa.Column("start_at", sa.DATETIME(), nullable=True))
    op.add_column("sale", sa.Column("end_at", sa.DATETIME(), nullable=True))
    op.add_column("sale", sa.Column("name", sa.TEXT(), nullable=True))

    op.drop_column("sale", "slug")
    op.drop_column("rarity", "order")
    op.drop_column("product", "units_sold")
    # ### end Alembic commands ###
